const maindata = [
    {
        id: 1,
        title: "All",
        title2: "Recent",
        title3: "Music",
        title4: "Trending",
        title5: "Computer",
        title6: "News",
        title7: "Bollywood",
        title8: "Physics",
        title9: "Training",
        title10: "Superhero",
        title11: "T-Series",
        title12: "Dramedy",
    },
    {
        id: 2,
        title: "Food",
        title2: "Live",
        title3: "Watched",
        title4: "Seminars",
        title5: "Comedy",
        title6: "Trailers",
        title7: "Mantras",
        title8: "Gaming",
        title9: "Dubbing",
        title10: "Gadgets",
        title11: "Cricket",
        title12: "World Cup",
    },
    {
        id: 3,
        title: "Nature",
        title2: "India",
        title3: "Thoughts",
        title4: "Bodybuildin",
        title5: "New to you",
        title6: "Lessons",
        title7: "Stocks",
        title8: "Sports",
        title9: "Shopping",
        title10: "Science",
        title11: "TV",
        title12: "Clothes",
    }
];
export default maindata